version: "3.8"

services:

  backend:
    image: python:latest
    build:
      context: .
      dockerfile: Dockerfile
    # command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "127.0.0.1:8000:8000"
    restart: always
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresqldata
    environment:
      POSTGRES_DB: bookdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: user123
    restart: unless-stopped
  pgadmin:
    image: pgadmin

volumes:
  data: